# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
