# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_preson_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preson',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='birth2'),
        ),
    ]
