# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201123_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preson',
            name='update_time',
        ),
        migrations.AddField(
            model_name='preson',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preson',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
