# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20201123_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preson',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
