# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201123_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preson',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], max_length=2),
        ),
    ]
