# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20201123_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='app01.Author'),
        ),
    ]
