# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='app01.Author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app01.Press'),
        ),
    ]
