# Generated by Django 3.1.3 on 2020-11-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10, verbose_name='书名')),
                ('book_author', models.ManyToManyField(to='book_os.Author', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=20, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_name', models.CharField(max_length=10, verbose_name='出版社名称')),
                ('press_book', models.ManyToManyField(to='book_os.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.IntegerField(verbose_name='文件标题')),
                ('file_path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_os.book')),
            ],
        ),
    ]
