# Generated by Django 3.1.3 on 2020-11-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_os', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
    ]
