# Generated by Django 3.1.3 on 2020-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_os', '0002_remove_author_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='press_book',
        ),
        migrations.AddField(
            model_name='book',
            name='press_book',
            field=models.ManyToManyField(to='book_os.Press'),
        ),
    ]
