# Generated by Django 3.1.3 on 2020-11-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_os', '0003_auto_20201120_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='press_book',
            new_name='book_press',
        ),
    ]
