# Generated by Django 3.1.3 on 2020-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_os', '0004_auto_20201120_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.ManyToManyField(to='book_os.BookFile'),
        ),
    ]
