# Generated by Django 3.1.3 on 2020-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_os', '0005_auto_20201120_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='file_title',
            field=models.CharField(max_length=20, verbose_name='文件标题'),
        ),
    ]
