# Generated by Django 3.1.4 on 2020-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201206_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuses',
            options={'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': '合同模板表', 'verbose_name_plural': '合同模板表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户列表', 'verbose_name_plural': '客户列表'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='咨询日期'),
        ),
    ]
