# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201116_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Press'),
        ),
    ]
