# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201116_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('books', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
