# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_bookfile_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='filename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.BookFile'),
        ),
    ]
