# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20201116_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='filename',
        ),
        migrations.AddField(
            model_name='book',
            name='filename',
            field=models.ManyToManyField(to='app01.BookFile'),
        ),
    ]
